# settings for cz_president_2018 block
# will be join with general settings

block_code: "cz_president_2018_history"

# block path from app root
block_path_url: "blocks/cz_president_2018_history/"
block_path_dir: "blocks/cz_president_2018_history/"

# reverse path to app root
block_reverse_path_dir: "../../../"

# external + local css, js
include_files:
    local_js:
        - "d3.min.js"
        # - "jquery-3.1.1.slim.min.js"
        - "metricsgraphics.min.js"
    local_css:
        - metricsgraphics.css
